### ISSUE TITLE
Empty xml

### ISSUE THREAD

**Issue by olee** [doccaz/kvm-scripts#1]
Somehow for me there does not seem to be any xml on stdin, preventing this script from working.
This is in my journalctl:
`... addForward[1740]: MACHINE_INFO:`
the MACHINE_INFO is just empty....

**Comment by doccaz** [comment]
Is the libvirtd service started?
Also, what does 'virsh dumpxml <VM NAME>' returns?

**Comment by olee** [comment]
Libvirtd is running of course (as I'm using that to launch my VMs and isn't it also responsible for calling the script?).
Also virsh dumpxml properly prints the whole xml of my vm

**Comment by doccaz** [comment]
Are you using the bash version? Could you try the Python version?

**Comment by olee** [comment]
Bash version - it seems it does not receive any stdin at all.
So I'm not sure if it really has to do something with the script or with libvirt/kvm/qemu

**Comment by doccaz** [comment]
That is weird. I could not get it to work on a newly installed machine (in fact, the $(cat; echo x) is not working on it at all). It still works on another machine with an older system version. Something changed. The python version is working fine though. Will make a simpler python version with just the port forwarding soon.

**Comment by olee** [comment]
Ok it's good to know that it wasn't my fault in any way 😅 
However if the bash version does not work (no stdin), wouldn't that mean the same for the python version?
At least if it uses the stdin to get the VM xml.
However I have an idea: How about just calling `virsh dumpxml <VM>` from the bash script itself?

**Comment by doccaz** [comment]
Should be solved by the latest commit, please check.
