### ISSUE TITLE
Inconsistent usage of ACTION states

### ISSUE THREAD

**Issue by Raimund-G** [doccaz/kvm-scripts#2]
```
if [ "${ACTION}" == "stopped" ] || [ "${ACTION}" == "reconnect" ]; then
     IPTABLES_ACTION="-D"
fi

if [ "${ACTION}" == "start" ] || [ "${ACTION}" == "reconnect" ]; then
     IPTABLES_ACTION="-I"
fi
```

So if ACTION is "reconnect" then IPTABLES_ACTION is first assigned "-D" which is then overwritten by "-I". The Python script has the same logic.
Does this make sense?

```
if [ "${ACTION}" == "prepare" ] || [ "${ACTION}" == "started" ] || [ "${ACTION}" == "stopped" ]; then
     log "domain $VM is in prepare, started or stopped, ignoring." 
     exit 0
fi
```

If ACTION is "stopped" then IPTABLES_ACTION is assigned "-D" but then no action is taken because the domain is ignored. The Python script doesn't care for "prepare" or "started" at all.
Does that make sense?

**Comment by doccaz** [comment]
Appears to be solved by the latest commit, please check.
