### ISSUE TITLE
qemu hook stopped/release not getting bridge name anymore

### ISSUE THREAD

**Issue by siarsky** [doccaz/kvm-scripts#3]
Hi @doccaz,

I've done some adjustments to your script:

1. fixing a bug: XML does not contain the bridge name in stopped/release actions anymore. The bridge is removed from XML before calling qemu "stopped/release" hook. I am using virsh version 5.0.0 on debian 10. As a side effect #1 is fixed as well, no "cat" is needed anymore, user specify the bridge on his own. How to test if the bug exists in your setup, stop VM and call 
`virsh dumpxml <VM> | xpath -q -e /domain/devices/interface[1]/source`
in my case stopped VMs do not have the bridge.
2. fixing of double usage of "reconnect" action (bug #2)
3. host IP can be specified as well, which allows to configure "all ports forwarding" from a specific external IP to a guest IP (I've used your script to achieve a solution described in [this article](https://www.cyberciti.biz/faq/kvm-forward-ports-to-guests-vm-with-ufw-on-linux/))
4. assign/remove host IP to/from network interface when VM starts/stops. Why? Example: if guests and host have ssh running on the port 22 (possible in my script adaption) and a guest will be stopped, SSH trafic of the guest will be processed by the host leading to ECDSA key mismatch (and difficult debugging of network problems)
5. code refactoring - the script in "my" taste in PS

Feel free to use the version in PS/part of it or just keep it here for the others.

Thank you, a nice idea!
Brani

PS:
```
#!/bin/bash
#
# Hook script for QEMU
# 
# adds port forwards via IPtables to your VMs
#
# Erico Mendonca (erico.mendonca@suse.com)
# dec/2018
#
# https://github.com/doccaz/kvm-scripts
#
# Adapted by Branislav Siarsky
# apr/2020
#

log() {
        logger -t addForward "$1"
}

addForward() {
   VM=$1
   HOST_NIC=$2
   HOST_IP=$3
   HOST_PORT=$4
   GUEST_NIC=$5
   GUEST_IP=$6
   GUEST_PORT=$7

   IPTABLES="/usr/sbin/iptables"
   IP="/usr/sbin/ip"
   HOST_IP_MASK="24"
   IPTABLES_ACTION=""
   IPTABLES_TEXT=""
   IP_ACTION=""
   IP_TEXT=""
   
   if [ "${VM}" == "${VM_NAME}" ]; then
	   if [ "${ACTION}" == "stopped" ]; then
		   IPTABLES_ACTION="-D"
		   IPTABLES_TEXT="Removing forwarding rules for VM ${VM}"
		   IP_ACTION="del"
		   IP_TEXT="Removing IP ${HOST_IP} from ${HOST_NIC}"
	   fi
	
	   if [ "${ACTION}" == "start" ] || [ "${ACTION}" == "reconnect" ]; then
		   IPTABLES_ACTION="-I"
		   IPTABLES_TEXT="Adding forwarding rules for VM ${VM}: host port ${HOST_PORT} will be redirected to ${GUEST_IP}:${GUEST_PORT} on interface ${GUEST_NIC}"
		   IP_ACTION="add"
		   IP_TEXT="Adding IP ${HOST_IP} to ${HOST_NIC}"
	   fi
	
	   if [ "${IPTABLES_ACTION}" == "" ]; then
		   log "Action ${ACTION} on domain $VM not configured, ignoring"
		   exit 0
	   else 
		   log "Action ${ACTION} on domain $VM called"
	   fi
	     
	   log "${IPTABLES_TEXT}"
	   $IPTABLES ${IPTABLES_ACTION} FORWARD -o ${GUEST_NIC} -d $GUEST_IP -j ACCEPT
	   $IPTABLES -t nat ${IPTABLES_ACTION} PREROUTING -d $HOST_IP -p tcp --dport $HOST_PORT -j DNAT --to $GUEST_IP:$GUEST_PORT
	   
	   log "${IP_TEXT}"
	   $IP address ${IP_ACTION} ${HOST_IP}/${HOST_IP_MASK} dev ${HOST_NIC} 
   fi
}

## main program
VM_NAME=${1}
ACTION=${2}

### declare your port forwards here
### format: addForward <VM> <source nic> <source address> <source port> <destination nic> <destination address> <destination port>
#Port 80 forward:   addForward debian10-vm2 enp3s0f0 192.168.1.17 80 virbr0 192.168.122.2 80
#All ports forward: addForward debian10-vm2 enp3s0f0 192.168.1.17 1:65535 virbr0 192.168.122.2 1-65535
addForward debian10-vm1 enp3s0f0 192.168.1.16 1:65535 virbr0 192.168.122.16 1-65535
addForward debian10-vm2 enp3s0f0 192.168.1.17 1:65535 virbr0 192.168.122.17 1-65535
addForward debian10-vm3 enp3s0f0 192.168.1.18 1:65535 virbr0 192.168.122.18 1-65535

```

**Comment by doccaz** [comment]
Thank you for your contribution! Merged your changes.
