### ISSUE TITLE
Readme doesn't match the script

### ISSUE THREAD

**Issue by seperman** [doccaz/kvm-scripts#5]
I'm trying to get the port forwarding work on kvm and got to your script!

In the readme it says:

`addForward <VM NAME> <external port> <internal IP> <internal port>`

But in the script it says:

`addForward <VM> <source nic> <source address> <source port> <destination nic> <destination address> <destination port> <protocol>`

My goal is to make the specific port accessible from other laptop in my local network. So what should be the source NIC be?

**Comment by doccaz** [comment]
Hi, that would the physical interface that's connected to the outside world (probably eth0 or wlan0), followed by its address.

**Comment by doccaz** [comment]
oops, forgot to close the issue.
