### ISSUE TITLE
Script hard locks vm host

### ISSUE THREAD

**Issue by emoon** [doccaz/kvm-scripts#6]
Hi,

I tried to use your script but I'm running into a problem. When I have this line at the end of the file

```
addForward debian10 enp5s0 192.168.0.3 2222 virbr0 192.168.122.119 22 tcp
```

My machine will hard lock so I need to go and manually turn it off/on (ssh doesn't work anymore) any idea what could cause this?

**Comment by emoon** [comment]
Digging some more I found this in syslog

```
May 16 07:02:18 vm-host-1 addForward: Action start on domain debian10 called
May 16 07:02:18 vm-host-1 addForward: Adding forwarding rules for VM debian10: host port 2222 will be redirected to 192.168.122.119:22 on interface virbr0
May 16 07:02:18 vm-host-1 addForward: Adding IP 192.168.0.3 to enp5s0
May 16 07:02:18 vm-host-1 libvirtd[1240]: internal error: Child process (LC_ALL=C PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin /etc/libvirt/hooks/qemu debian10 start begin -) unexpected exit status 2: RTNETLINK answers: File exists
May 16 07:02:18 vm-host-1 libvirtd[1240]: Hook script execution failed: internal error: Child process (LC_ALL=C PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin /etc/libvirt/hooks/qemu debian10 start begin -) unexpected exit status 2: RTNETLINK answers: File exists
```

It's likely something local on my side so closing this.

**Comment by doccaz** [comment]
Oh you need to adapt the rules to your environment if that is the case.

That line is just a sample. It's possible that rule coincidentally added a
firewall that redirected the traffic for your own machine in an invalid
way.

**Comment by emoon** [comment]
The thing is that the lines generated by the scripts are correct and if I run them manually everything works, but when they are executed from the script the above thing happens. I'm not really sure why and I haven't investigated it futher.
