### ISSUE TITLE
Guest to guest communication through host (forwarded port) not working

### ISSUE THREAD

**Issue by se1by** [doccaz/kvm-scripts#8]
Hey,
first of all: thanks for your work!

I got this forward:
`addForward testvm1 enp0s31f6 <public_ip> 30001 virbr0 192.168.122.38 30001 tcp`

This works flawlessly from any other host. If I try to connect to this port from the host, I get a connection refused. If I try to connect from another guest, I get a timeout. My guess is that it's not going through `enp0s31f6`, but I can't seem to figure out how to solve this. Any help would be appreciated! 
 
In case it matters, I tested this by running `netcat -l -p 30001` on testvm1 and `date|netcat <public_ip> 30001` from everything else.

**Comment by se1by** [comment]
I switched to writing my own hook script (https://github.com/se1by/libvirt-hook-nftables in case you're interested). I don't limit the rule to a specific device, so guest to guest communication works for me.

**Comment by doccaz** [comment]
Thanks. I'll link your script on the README.
